<?php
if($page=="create-supplier"){
	$found=include("views/pages/ui/supplier/create_supplier.php");
}elseif($page=="edit-supplier"){
	$found=include("views/pages/ui/supplier/edit_supplier.php");
}elseif($page=="suppliers"){
	$found=include("views/pages/ui/supplier/manage_supplier.php");
}elseif($page=="details-supplier"){
	$found=include("views/pages/ui/supplier/details_supplier.php");
}elseif($page=="view-supplier"){
	$found=include("views/pages/ui/supplier/view_supplier.php");
}
?>
