<?php
//--- This code is generated by ProBot ---
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Manufacturer;
use App\Models\Category;
use App\Models\Section;
use App\Models\UoM;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class ProductController extends Controller{

	public function index(){
		$products=Product::paginate(10);
		return view("pages.erp.product.index_product",["products"=>$products]);
	}
	public function create(){
		$manufacturers=Manufacturer::all();
		$categories=Category::all();
		$sections=Section::all();
		$uom=UoM::all();

		return view("pages.erp.product.create_product",["manufacturers"=>$manufacturers,"categories"=>$categories,"sections"=>$sections,"uom"=>$uom]);
	}
	public function store(Request $request){
//		Product::create($request->all());
		$product=new Product;
		$product->name=$request->txtName;
		$product->offer_price=$request->txtOffer_price;
		$product->manufacturer_id=$request->cmbManufacturerId;
		$product->regular_price=$request->txtRegular_price;
		$product->description=$request->txtDescription;
		if(isset($request->filePhoto)){
		$product->photo=$request->filePhoto;
		}
		$product->category_id=$request->cmbCategoryId;
		$product->section_id=$request->cmbSectionId;
		$product->is_featured=$request->txtIs_featured;
		$product->star=$request->txtStar;
		$product->is_brand=$request->txtIs_brand;
		$product->offer_discount=$request->txtOffer_discount;
		$product->uom_id=$request->cmbUoMId;
		$product->weight=$request->txtWeight;
		$product->barcode=$request->txtBarcode;

		$product->save();
		if(isset($request->filePhoto)){
			$imageName = $product->id.'.'.$request->filePhoto->extension();
			$product->photo=$imageName;
			$product->update();
			$request->filePhoto->move(public_path('img'),$imageName);
		}
		return back()->with('success','Created Successfully.');
  
	}
	public function show($id){
		$product=Product::find($id);
		return view("pages.erp.product.show_product",["product"=>$product]);
	}
	public function edit(Product $product){
		$manufacturers=Manufacturer::all();
		$categories=Category::all();
		$sections=Section::all();
		$uom=UoM::all();

		return view("pages.erp.product.edit_product",["product"=>$product,"manufacturers"=>$manufacturers,"categories"=>$categories,"sections"=>$sections,"uom"=>$uom]);
	}
	public function update(Request $request,Product $product){
//		$product->update($request->all());
		$product->name=$request->txtName;
		$product->offer_price=$request->txtOffer_price;
		$product->manufacturer_id=$request->cmbManufacturerId;
		$product->regular_price=$request->txtRegular_price;
		$product->description=$request->txtDescription;
		if(isset($request->filePhoto)){
		$product->photo=$request->filePhoto;
		}
		$product->category_id=$request->cmbCategoryId;
		$product->section_id=$request->cmbSectionId;
		$product->is_featured=$request->txtIs_featured;
		$product->star=$request->txtStar;
		$product->is_brand=$request->txtIs_brand;
		$product->offer_discount=$request->txtOffer_discount;
		$product->uom_id=$request->cmbUoMId;
		$product->weight=$request->txtWeight;
		$product->barcode=$request->txtBarcode;

		if(isset($request->filePhoto)){
			$imageName = $product->id.'.'.$request->filePhoto->extension();
			$product->photo=$imageName;
			$request->filePhoto->move(public_path('img'),$imageName);
		}
		$product->update();
		return redirect()->route("products.index")->with('success','Updated Successfully.');
    
	}
	public function destroy(Product $product){
		$product->delete();
		return redirect()->route("products.index")->with('success','Deleted Successfully.');
	}
}
